service: serverless-demo-infra

provider:
  name: aws
  runtime: python3.8
  stage: ${self:custom.stage}

custom:
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
  stage: ${opt:stage}
  config:
    dev:
      account_id: '664096853771'
    stg:
      account_id: '723706874016'

resources:
- ${file(dynamodb.yml)}