Resources:
  EmmLambdaPingExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EmmLambdaPingExecutionRole
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  EmmLambdaItemsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EmmLambdaItemsExecutionRole
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - Ref: EmmLambdaItemsExecutionPolicy