Resources:
  EmmLambdaItemsExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: EmmLambdaItemsExecutionPolicy
      Description: Politica lambda items demo serverless
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:*Item
          - dynamodb:Scan
          - dynamodb:Query
          Resource:
          - arn:aws:dynamodb:us-east-1:${self:custom.config.${self:custom.stage}.account_id}:table/demo-serverless-items