service: serverless-demo

provider:
  name: aws
  runtime: python3.8
  stage: ${self:custom.stage}

custom:
  pythonRequirements:
    dockerizePip: non-linux
    fileName: requirements.txt
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
  stage: ${opt:stage}
  config:
    dev:
      account_id: '664096853771'
      memory_size: 128
    stg:
      memory_size: 128
      account_id: '723706874016'
    prd:
      memory_size: 256
      account_id: '691789668597' #to be defined
  
functions:
  ping:
    handler: ping.lambda_handler
    events:
      - http:
          method: GET
          path: /ping
          private: false
    timeout: 600
    role: arn:aws:iam::${self:custom.config.${self:custom.stage}.account_id}:role/EmmLambdaPingExecutionRole
    tags:
      Name: master-builder-ping